"""add posting_url to jobs

Revision ID: fcfb647a008b
Revises: c85660226ee5
Create Date: 2026-07-31 16:26:08.403522

"""
from alembic import op
import sqlalchemy as sa


revision = 'fcfb647a008b'
down_revision = 'c85660226ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('posting_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'posting_url')
    # ### end Alembic commands ###
